# Generated by Django 4.1.6 on 2023-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeasures",
            name="measurefield",
            field=models.JSONField(default=dict, verbose_name="measurefield"),
        ),
    ]
