# Generated by Django 4.1.6 on 2023-08-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_alter_usermeasures_measurefield"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermeasures", name="measure_owner",),
    ]
